from __future__ import annotations
import argparse, csv, hashlib, json, random, statistics, sys, time
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

ROOT=Path(__file__).resolve().parent; DATA=ROOT/'data'; OUTPUT=ROOT/'output'
REPORT_MIN=30; RELEASE_MIN=15
BLOCKING={'UNAVAILABLE','LEAVE','TRAINING'}
BASES={'EBAW','EBLG'}

@dataclass(frozen=True)
class Mission:
    id:str; origin:str; destination:str; departure:datetime; arrival:datetime; pax:int; fixed_aircraft:str
@dataclass(frozen=True)
class Pilot:
    id:str; role:str; home_base:str; max_duty_min:int

def dt(x): return datetime.fromisoformat(x)
def load_data():
    pilots={}; avail={}; missions=[]
    with (DATA/'pilots.csv').open(newline='',encoding='utf-8') as f:
        for r in csv.DictReader(f): pilots[r['id']]=Pilot(r['id'],r['role'].upper(),r['home_base'],int(r.get('max_duty_min') or 600))
    p=DATA/'pilot_availability.csv'
    if p.exists():
        with p.open(newline='',encoding='utf-8') as f:
            for r in csv.DictReader(f):
                try: avail[(r['pilot_id'],dt(r['date']).date())]=(r.get('status') or 'AVAILABLE').upper()
                except Exception: pass
    with (DATA/'missions.csv').open(newline='',encoding='utf-8') as f:
        for r in csv.DictReader(f):
            kind=(r.get('type') or r.get('movement_type') or 'MISSION').strip().upper()
            if kind in {'EMPTY','EMPTY_LEG','HISTORICAL_EMPTY','POSITION','POSITIONING'}: continue
            dep=dt(r['departure']); arrtxt=(r.get('arrival') or '').strip()
            # If arrival is absent, use estimates generated by the existing application when available.
            arr=dt(arrtxt) if arrtxt else None
            missions.append([r,dep,arr])
    estimates={}
    ep=DATA/'missions_with_estimates.csv'
    if ep.exists():
        with ep.open(newline='',encoding='utf-8') as f:
            for r in csv.DictReader(f):
                if r.get('arrival'): estimates[r['id']]=dt(r['arrival'])
    out=[]
    for r,dep,arr in missions:
        arr=arr or estimates.get(r['id']) or (dep+timedelta(hours=2))
        reg=(r.get('fixed_aircraft') or '').strip().upper().replace('-','')
        if not reg: raise ValueError(f"Mission {r['id']} has no fixed_aircraft. Lean optimizer requires fixed aircraft.")
        out.append(Mission(r['id'],r['origin'],r['destination'],dep,arr,int(r.get('pax') or 0),reg))
    return sorted(out,key=lambda m:(m.departure,m.id)),pilots,avail

def available(pid,m,avail):
    d=m.departure.date()
    while d<=m.arrival.date():
        if avail.get((pid,d),'AVAILABLE') in BLOCKING: return False
        d+=timedelta(days=1)
    return True

def duty_interval(m): return m.departure-timedelta(minutes=REPORT_MIN),m.arrival+timedelta(minutes=RELEASE_MIN)
def overlap(a,b): return a[0]<b[1] and b[0]<a[1]

def precompute(missions,pilots,avail):
    caps=[p.id for p in pilots.values() if p.role=='CAPT']; fos=[p.id for p in pilots.values() if p.role=='FO']
    feasible={}
    for m in missions:
        feasible[m.id]={'CAPT':[p for p in caps if available(p,m,avail)],'FO':[p for p in fos if available(p,m,avail)]}
        if not feasible[m.id]['CAPT'] or not feasible[m.id]['FO']:
            raise ValueError(f"{m.id} has no available {'captain' if not feasible[m.id]['CAPT'] else 'first officer'}")
    return feasible,caps,fos

def can_assign(pid,m,busy):
    iv=duty_interval(m)
    return all(not overlap(iv,x) for x in busy.get(pid,[]))

def build_tours(missions):
    """Split each fixed-aircraft sequence into crew tours.

    A crew stays attached while the aircraft is outstation. A tour ends only
    when the aircraft arrives at EBAW or EBLG. This makes outstation swaps
    impossible by construction instead of trying to enforce continuity one
    mission at a time in global chronological order.
    """
    by_aircraft={}
    for m in missions:
        by_aircraft.setdefault(m.fixed_aircraft,[]).append(m)
    tours=[]
    for reg, seq in by_aircraft.items():
        seq=sorted(seq,key=lambda m:(m.departure,m.id))
        current=[]
        for m in seq:
            current.append(m)
            if m.destination in BASES:
                tours.append((reg,current))
                current=[]
        if current:
            tours.append((reg,current))
    return sorted(tours,key=lambda x:(x[1][0].departure,x[0]))

def decode(keys,missions,feasible,caps,fos,rng=None):
    """Crew continuity with exceptional outstation replacement.

    Outstation, an incumbent CAPT/FO is always retained when feasible.
    A replacement is allowed only for a role whose incumbent cannot continue
    because of availability or overlap. At EBAW/EBLG normal rebalancing is
    allowed.
    """
    busy={}; counts={p:0 for p in caps+fos}; days={p:set() for p in caps+fos}; assign={}; meta={}
    by_aircraft={}
    for m in missions: by_aircraft.setdefault(m.fixed_aircraft,[]).append(m)
    gi=0

    def pick(role,pool,m,incumbent=None):
        nonlocal gi
        options=[p for p in pool if p in feasible[m.id][role] and can_assign(p,m,busy)]
        if not options: return None
        if incumbent in options: return incumbent
        ranked=sorted(options,key=lambda p:(counts[p],len(days[p]),p))
        gene=keys[gi % len(keys)] if keys else 0.0; gi+=1
        width=max(1,(len(ranked)+1)//2)
        return ranked[min(width-1,int(gene*width))]

    for reg,seq in sorted(by_aircraft.items()):
        seq=sorted(seq,key=lambda m:(m.departure,m.id))
        old_c=old_f=None; previous_destination=None
        for m in seq:
            at_base=(previous_destination in BASES) if previous_destination is not None else True
            captain=pick('CAPT',caps,m,None if at_base else old_c)
            fo=pick('FO',fos,m,None if at_base else old_f)
            if captain is None or fo is None: return None

            changed_c=old_c is not None and captain!=old_c
            changed_f=old_f is not None and fo!=old_f
            outstation=previous_destination is not None and previous_destination not in BASES
            if old_c is None:
                action='INITIAL_ATTACH'
            elif not changed_c and not changed_f:
                action='CONTINUE'
            elif outstation:
                action=('OUTSTATION_FULL_CREW_SWAP' if changed_c and changed_f
                        else 'OUTSTATION_CAPT_SWAP' if changed_c else 'OUTSTATION_FO_SWAP')
            else:
                action=('BASE_FULL_CREW_SWAP' if changed_c and changed_f
                        else 'BASE_CAPT_SWAP' if changed_c else 'BASE_FO_SWAP')

            assign[m.id]={'captain':captain,'fo':fo}
            meta[m.id]={'action':action,
                        'handover_airport':previous_destination if 'SWAP' in action else None,
                        'outstation':bool(outstation and (changed_c or changed_f)),
                        'changed_pilots':int(changed_c)+int(changed_f)}
            for pid in (captain,fo):
                busy.setdefault(pid,[]).append(duty_interval(m))
                counts[pid]+=1; days[pid].add(m.departure.date())
            old_c,old_f=captain,fo; previous_destination=m.destination
    return assign,counts,days,meta

def score(decoded,missions,pilots,avail,caps,fos):
    assign,counts,days,meta=decoded
    out_events=sum(1 for x in meta.values() if x['outstation'])
    out_changed=sum(x['changed_pilots'] for x in meta.values() if x['outstation'])

    vals=[]
    for pool in (caps,fos):
        c=[counts[p] for p in pool]; d=[len(days[p]) for p in pool]
        vals += [statistics.pvariance(c) if len(c)>1 else 0,
                 statistics.pvariance(d) if len(d)>1 else 0]
    balance=vals[0]+vals[2]+0.5*(vals[1]+vals[3])

    byday={}
    for m in missions: byday.setdefault(m.departure.date(),[]).append(m)
    reserve_short=0; reserve_total=0
    for day,ms in byday.items():
        active_c={assign[m.id]['captain'] for m in ms}; active_f={assign[m.id]['fo'] for m in ms}
        avc=sum(avail.get((p,day),'AVAILABLE') not in BLOCKING for p in caps)-len(active_c)
        avf=sum(avail.get((p,day),'AVAILABLE') not in BLOCKING for p in fos)-len(active_f)
        reserve_short += max(0,1-avc)+max(0,1-avf)
        reserve_total += max(0,avc)+max(0,avf)

    base_swaps=sum(1 for x in meta.values() if x['action'].startswith('BASE_') and 'SWAP' in x['action'])
    # Strict lexicographic priority.
    return (out_events,out_changed,balance,reserve_short,base_swaps,-reserve_total)

def build_crew_actions(assign, missions, handover_meta):
    """Return explicit crew-continuity / handover actions for the GUI."""
    actions = []
    for m in missions:
        pair = assign[m.id]
        action_meta = handover_meta.get(m.id, {})
        actions.append({
            "mission": m.id,
            "aircraft": m.fixed_aircraft,
            "captain": pair["captain"],
            "fo": pair["fo"],
            "action": action_meta.get("action", "CONTINUE"),
            "handover_airport": action_meta.get("handover_airport"),
            "changed_pilots": action_meta.get("changed_pilots", 0),
            "nonhome_swap_event": int(action_meta.get("outstation", False)),
        })
    return actions

def make_solution(decoded,scorev,missions,pilots):
    assign,counts,days,meta=decoded; routes={}; movements={}; actions={}
    for m in missions:
        reg=m.fixed_aircraft; routes.setdefault(reg,[]).append(m.id)
        actions.setdefault(reg,[]).append({'mission':m.id,'transition_mode':'FIXED'})
        pair=assign[m.id]
        movements.setdefault(reg,[]).append({'type':'MISSION','mission':m.id,'from':m.origin,'to':m.destination,
            'start':m.departure.isoformat(),'end':m.arrival.isoformat(),'pax':m.pax,'purpose':'CUSTOMER',
            'captain':pair['captain'],'fo':pair['fo']})
    pilot_days={p:sorted(x.isoformat() for x in ds) for p,ds in days.items() if ds}
    sig=hashlib.sha1(json.dumps(assign,sort_keys=True).encode()).hexdigest()[:12]
    charged=sum(len(x) for x in days.values())
    out_events,out_changed,balance,reserve_short,base_swaps,neg_reserve=scorev
    changed_total=sum(x['changed_pilots'] for x in meta.values())
    return {'schedule_signature':sig,'pilot_days_by_pilot':pilot_days,
      'objectives':{'total_operational_cost_eur':float(charged*600),'complexity_score':int(base_swaps+out_events),
        'empty_legs':0,'charged_pilot_days':charged,'aircraft_parking_days':0,'crew_balance_score':round(balance,4),
        'backup_shortage_days':int(reserve_short),'outstation_handovers':int(out_events)},
      'cost_breakdown':{'pilot_cost_eur':float(charged*600),'commercial_flight_cost_eur':0.0,'empty_flight_cost_eur':0.0},
      'metrics':{'empty_nm':0.0,'empty_legs':0,'charged_pilot_days':charged,'aircraft_parking_days':0,
        'changed_pilot_count':int(changed_total),'nonhomebase_swap_events':int(out_events),
        'outstation_changed_pilots':int(out_changed),'base_handovers':int(base_swaps),
        'crew_return_pilots':0,'inbound_crew_deadhead_pilots':0,'crew_balance_score':round(balance,4),
        'backup_shortage_days':int(reserve_short),'backup_slots':int(-neg_reserve),'mission_count_by_pilot':counts},
      'routes':routes,'aircraft_movements':movements,'aircraft_actions':actions,'crew_assignments':assign,
      'crew_actions':build_crew_actions(assign, missions, meta),'final_crew_decisions':[],
      'validation':{'fixed_aircraft':True,'pilot_availability_valid':True,'pilot_overlap_valid':True}}

def tournament(pop,rng):
    a,b=rng.sample(pop,2); return a if a['score']<b['score'] else b


def save(solutions,stats):
    OUTPUT.mkdir(exist_ok=True)
    # Preserve live file only; replace optimizer result set.
    for p in OUTPUT.glob('pareto_*.json'): p.unlink()
    sols=sorted(solutions,key=lambda s:(s['objectives'].get('outstation_handovers',0),s['objectives']['crew_balance_score'],s['objectives']['backup_shortage_days'],s['objectives']['complexity_score']))
    unique=[]; seen=set()
    for s in sols:
        if s['schedule_signature'] not in seen: seen.add(s['schedule_signature']); unique.append(s)
    unique=unique[:100]
    for i,s in enumerate(unique[:30]):
        s=dict(s); s['pareto_index']=i; (OUTPUT/f'pareto_{i:03d}.json').write_text(json.dumps(s,indent=2),encoding='utf-8')
    fields=['solution_index','schedule_signature','total_operational_cost_eur','complexity_score','empty_legs','charged_pilot_days','aircraft_parking_days','empty_nm','crew_balance_score','backup_shortage_days']
    with (OUTPUT/'pareto.csv').open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=fields); w.writeheader()
        for i,s in enumerate(unique[:30]):
            o=s['objectives']; w.writerow({'solution_index':i,'schedule_signature':s['schedule_signature'],'total_operational_cost_eur':o['total_operational_cost_eur'],'complexity_score':o['complexity_score'],'empty_legs':0,'charged_pilot_days':o['charged_pilot_days'],'aircraft_parking_days':0,'empty_nm':0,'crew_balance_score':o['crew_balance_score'],'backup_shortage_days':o['backup_shortage_days']})
    (OUTPUT/'diverse_solutions.json').write_text(json.dumps(unique,indent=2),encoding='utf-8')
    if unique: (OUTPUT/'cheapest.json').write_text(json.dumps(unique[0],indent=2),encoding='utf-8')
    (OUTPUT/'run_summary.json').write_text(json.dumps(stats|{'solutions':len(unique),'optimizer':'LEAN_CREW_GA'},indent=2),encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(description='Lean GA: fixed missions/aircraft, optimize crew balance and reserve coverage.')
    ap.add_argument('--population',type=int,default=40); ap.add_argument('--generations',type=int,default=30); ap.add_argument('--runs',type=int,default=2); ap.add_argument('--seed',type=int,default=42); ap.add_argument('--verbose',action='store_true'); ap.add_argument('--debug',action='store_true'); ap.add_argument('--live',action='store_true'); ap.add_argument('--live-every',type=int,default=1)
    a=ap.parse_args(); missions,pilots,avail=load_data(); feasible,caps,fos=precompute(missions,pilots,avail)
    print(f'LEAN CREW GA · missions={len(missions)} fixed aircraft · captains={len(caps)} · FOs={len(fos)}')
    print('Priority: feasibility -> MIN outstation handovers -> crew balance -> backup coverage -> base handovers')
    archive={}; start=time.perf_counter(); evals=0
    for run in range(a.runs):
        rng=random.Random(a.seed+run*10007); n=max(2,len(missions)*2)
        pop=[]
        for _ in range(a.population):
            genes=[rng.random() for _ in range(n)]; dec=decode(genes,missions,feasible,caps,fos,rng); sc=score(dec,missions,pilots,avail,caps,fos) if dec else (10**9,10**9,10**9,10**9,10**9,0); pop.append({'genes':genes,'decoded':dec,'score':sc}); evals+=1
        for gen in range(a.generations):
            children=[]
            while len(children)<a.population:
                p1=tournament(pop,rng); p2=tournament(pop,rng); cut=rng.randrange(n) if n else 0; g=p1['genes'][:cut]+p2['genes'][cut:]
                for _ in range(1+(rng.random()<0.25)):
                    if n: g[rng.randrange(n)]=rng.random()
                dec=decode(g,missions,feasible,caps,fos,rng); sc=score(dec,missions,pilots,avail,caps,fos) if dec else (10**9,10**9,10**9,10**9,10**9,0); children.append({'genes':g,'decoded':dec,'score':sc}); evals+=1
            pop=sorted(pop+children,key=lambda x:x['score'])[:a.population]
            if a.verbose and (gen%5==0 or gen==a.generations-1):
                b=pop[0]['score']; print(f'run={run+1}/{a.runs} gen={gen+1}/{a.generations} outstation={b[0]} balance={b[2]:.3f} backup_shortage={b[3]} base_handovers={b[4]} elapsed={time.perf_counter()-start:.1f}s',flush=True)
        for x in pop[:20]:
            if x['decoded']:
                s=make_solution(x['decoded'],x['score'],missions,pilots); archive[s['schedule_signature']]=s
    save(list(archive.values()),{'runs':a.runs,'population':a.population,'generations':a.generations,'total_evaluations':evals,'seed':a.seed,'elapsed_seconds':round(time.perf_counter()-start,2)})
    if not archive:
        print('NO FEASIBLE CREW SCHEDULE FOUND.')
        print('Outstation continuity is preferred; a role is replaced only when its incumbent cannot continue.')
        print('Likely causes: a crew member becomes unavailable mid-tour, or all eligible crews overlap with another tour.')
        return 2
    best=min(archive.values(),key=lambda s:(s['objectives'].get('outstation_handovers',0),s['objectives']['crew_balance_score'],s['objectives']['backup_shortage_days'],s['objectives']['complexity_score']))
    print(f"DONE · outstation={best['objectives'].get('outstation_handovers',0)} · balance={best['objectives']['crew_balance_score']} · backup shortage={best['objectives']['backup_shortage_days']} · handovers={best['objectives']['complexity_score']} · {time.perf_counter()-start:.1f}s")
    return 0
if __name__=='__main__': raise SystemExit(main())
